In [1]:
import pandas as pds
import numpy as npy

In [2]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.T)

   a         b        c  d  e
0  1  0.065280      Bob  B  0
1  2  0.467896      Amy  o  1
2  3  0.867549  Michael  b  2
3  4  0.048746    Linda  o  3
         0         1         2         3
a        1         2         3         4
b  0.06528  0.467896  0.867549  0.048746
c      Bob       Amy   Michael     Linda
d        B         o         b         o
e        0         1         2         3


In [5]:
matrix = npy.random.randint(0,100,18).reshape(2,9)
print(matrix)
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.describe())

[[26 82 92 53 10 20 11 59 61]
 [58  1 39 76 32 36 39 61 76]]
    0   1   2   3   4   5   6   7   8
0  26  82  92  53  10  20  11  59  61
1  58   1  39  76  32  36  39  61  76
               0          1          2          3          4          5  \
count   2.000000   2.000000   2.000000   2.000000   2.000000   2.000000   
mean   42.000000  41.500000  65.500000  64.500000  21.000000  28.000000   
std    22.627417  57.275649  37.476659  16.263456  15.556349  11.313708   
min    26.000000   1.000000  39.000000  53.000000  10.000000  20.000000   
25%    34.000000  21.250000  52.250000  58.750000  15.500000  24.000000   
50%    42.000000  41.500000  65.500000  64.500000  21.000000  28.000000   
75%    50.000000  61.750000  78.750000  70.250000  26.500000  32.000000   
max    58.000000  82.000000  92.000000  76.000000  32.000000  36.000000   

              6          7          8  
count   2.00000   2.000000   2.000000  
mean   25.00000  60.000000  68.500000  
std    19.79899   1.414214  1

In [6]:
matrix = npy.arange(1, 19).reshape(2,9)
print(matrix)
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
data_frame_matrix = pds.DataFrame(matrix, index=list("甲乙"), columns = list("ABCDEFGHI"))
print(data_frame_matrix)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
    0   1   2   3   4   5   6   7   8
0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18
    A   B   C   D   E   F   G   H   I
甲   1   2   3   4   5   6   7   8   9
乙  10  11  12  13  14  15  16  17  18


In [7]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame_matrix = pds.DataFrame(matrix)
print(matrix)
renew_index = {"a": "x", "d": "y"}
data_frame_matrix = data_frame_matrix.rename(renew_index, axis=1) #axis=0
print(data_frame_matrix)

{'a': [1, 2, 3, 4], 'b': array([0.11939354, 0.8722508 , 0.26642631, 0.73970549]), 'c': ['Bob', 'Amy', 'Michael', 'Linda'], 'd': ['B', 'o', 'b', 'o'], 'e': 0    0
1    1
2    2
3    3
dtype: int64}
   x         b        c  y  e
0  1  0.119394      Bob  B  0
1  2  0.872251      Amy  o  1
2  3  0.266426  Michael  b  2
3  4  0.739705    Linda  o  3


In [8]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame_matrix = pds.DataFrame(matrix)

print(data_frame_matrix)
renew_index = {1: "one", 0: "zero"}
data_frame_matrix = data_frame_matrix.rename(renew_index, axis=0)
print(data_frame_matrix)

   a         b        c  d  e
0  1  0.122981      Bob  B  0
1  2  0.549562      Amy  o  1
2  3  0.818088  Michael  b  2
3  4  0.391249    Linda  o  3
      a         b        c  d  e
zero  1  0.122981      Bob  B  0
one   2  0.549562      Amy  o  1
2     3  0.818088  Michael  b  2
3     4  0.391249    Linda  o  3


In [7]:
dates_index = pds.date_range("20220101", periods=4)
print(dates_index)
data_frame_matrix.index = dates_index
print(data_frame_matrix)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04'], dtype='datetime64[ns]', freq='D')
            a         b        c  d  e
2022-01-01  1  0.485041      Bob  B  0
2022-01-02  2  0.396374      Amy  o  1
2022-01-03  3  0.756491  Michael  b  2
2022-01-04  4  0.303063    Linda  o  3


In [8]:
matrix = {
    "A": npy.arange(1,31),
    "B": npy.arange(31,61),
    "C": npy.arange(61,91),
    "D": npy.arange(91,121),
    "E": npy.arange(121,151),
}
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.head(2))
print(data_frame_matrix.tail()) #(3)

     A   B   C    D    E
0    1  31  61   91  121
1    2  32  62   92  122
2    3  33  63   93  123
3    4  34  64   94  124
4    5  35  65   95  125
5    6  36  66   96  126
6    7  37  67   97  127
7    8  38  68   98  128
8    9  39  69   99  129
9   10  40  70  100  130
10  11  41  71  101  131
11  12  42  72  102  132
12  13  43  73  103  133
13  14  44  74  104  134
14  15  45  75  105  135
15  16  46  76  106  136
16  17  47  77  107  137
17  18  48  78  108  138
18  19  49  79  109  139
19  20  50  80  110  140
20  21  51  81  111  141
21  22  52  82  112  142
22  23  53  83  113  143
23  24  54  84  114  144
24  25  55  85  115  145
25  26  56  86  116  146
26  27  57  87  117  147
27  28  58  88  118  148
28  29  59  89  119  149
29  30  60  90  120  150
   A   B   C   D    E
0  1  31  61  91  121
1  2  32  62  92  122
     A   B   C    D    E
25  26  56  86  116  146
26  27  57  87  117  147
27  28  58  88  118  148
28  29  59  89  119  149
29  30  60  90  120  150


In [ ]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
cols = data_frame.columns.tolist()
col_index = '活死'
cols.insert(2, col_index)
data_frame[col_index] = data_frame.Survived.apply(lambda z:'活'if z else'死')
data_frame.loc[:10, cols]

,PassengerId,Survived,活死,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,死,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,活,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,活,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,活,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,死,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,死,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,死,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,死,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,活,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,活,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [10]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame)
cols = ['Name','Age']
data_frame.drop(cols, axis=1, inplace=True)
print(data_frame)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [11]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
data_frame_train = data_frame.sample(frac=0.7)
display(data_frame_train)
data_frame_test = data_frame.drop(data_frame_train.index)
display(data_frame_test)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [12]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame)
data_frame_types = {"Survived": "bool"}
data_frame = pds.read_csv('http://bit.ly/kaggletrain', dtype=data_frame_types)
print(data_frame)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [13]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame.iloc[:50, 0:4])  #取0-49列的0-3欄
print(data_frame.iloc[:50, ::-1])  #col反向顯示
print(data_frame.iloc[::-1, 0:4])  #row反向顯示

    PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
2

In [14]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Linda', 'Michael', 'Amy'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame = pds.DataFrame(matrix)
print(data_frame)
print(data_frame.sort_values(by=['d']))
print(data_frame.sort_values(by=['d'], ascending=False))
print(data_frame.sort_values(by=['d', 'c']))


   a         b        c  d  e
0  1  0.207116      Bob  B  0
1  2  0.688689    Linda  o  1
2  3  0.544305  Michael  b  2
3  4  0.006267      Amy  o  3
   a         b        c  d  e
0  1  0.207116      Bob  B  0
2  3  0.544305  Michael  b  2
1  2  0.688689    Linda  o  1
3  4  0.006267      Amy  o  3
   a         b        c  d  e
1  2  0.688689    Linda  o  1
3  4  0.006267      Amy  o  3
2  3  0.544305  Michael  b  2
0  1  0.207116      Bob  B  0
   a         b        c  d  e
0  1  0.207116      Bob  B  0
2  3  0.544305  Michael  b  2
3  4  0.006267      Amy  o  3
1  2  0.688689    Linda  o  1
